### PR TITLE
Dan changes

### PR DESCRIPTION
**Pull request by DanDobrick**
Squashed commits per request

### CODE REVIEW

**Comment by daveWid** [comment]
Looks like you have too many commits in this PR. You only need to send over the 53eb7a1 commit.

**Comment by DanDobrick** [comment]
So should I squash all the commits down to the 53eb7a1 commit?

**Comment by daveWid** [comment]
No, I have all of the other commits in my repo, so I'm not quite sure why they are all coming over in the PR. I only need the last one.

**Comment by DanDobrick** [comment]
git was telling me that I was 1 commit behind what I had on GitHub so I tried figuring out what was going on, but it turned out deleting the branch on GitHub and re-pushing everything was easier than fixing whatever issue I had. Would that cause the issue you’re seeing? Did I mess everything up?

**Comment by daveWid** [comment]
Ya something is definitely wrong. Let me think a minute on the best way to get this fixed up...

**Comment by DanDobrick** [comment]
Closed. I created another pull request with only 1 commit.

**Pull request closed without merging**
